server:
  port: 8888
  servlet:
    context-path: /snms
  address: localhost
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/html/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/snms?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
